sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 14
before_install:
  - sudo apt-get install expect
  - sudo apt-get install libnotify-bin
install:
  - npm install
  - npm install -g @bullhorn/bullhorn-cli
  - npm install -g travis-deploy-once@4
script:
  - npm run build
after_success:
  - travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
